remote_theme: hardpool/hardpool-flat

# Build settings
markdown: kramdown
encoding: utf-8

# Site Settings
title                     : "Twinkle's portfolio"
title_separator           : "|"
favicon                   : /assets/fav.ico
similar_posts:
  tags_to_match: 2

# Site SEO
seo:
  gtmid: GTM-M3MXT24

# Site Header
main_logo                 : ""
name                      : "Twinkle Katoch"
description               : ""
header:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/twinklekatoch"

# site landing
landing:
  shop: <div id="ltkwidget-version-two225766876" data-appid="225766876" class="ltkwidget-version-two"><script>var rsLTKLoadApp="0",rsLTKPassedAppID="225766876";</script><script type="text/javascript" src="https://widgets-static.rewardstyle.com/widgets2_0/client/pub/ltkwidget/ltkwidget.js"></script><div widget-dashboard-settings="" data-appid="225766876" data-userid="331093" data-rows="1" data-cols="8" data-showframe="true" data-padding="4" data-profileid="94dc5dca-2f81-11ea-866a-0bef29f386d0"><div class="rs-ltkwidget-container"><div ui-view=""></div></div></div><noscript>This content requires JavaScript to be enabled, and the site or browser may be disabling it. Try reactivating it to view this content.</noscript></div>

# site post
post:
  sidebar: <div id="ltkwidget-version-two169386404" data-appid="169386404" class="ltkwidget-version-two"><script>var rsLTKLoadApp="0",rsLTKPassedAppID="169386404";</script><script type="text/javascript" src="https://widgets-static.rewardstyle.com/widgets2_0/client/pub/ltkwidget/ltkwidget.js"></script><div widget-dashboard-settings="" data-appid="169386404" data-userid="331093" data-rows="4" data-cols="2" data-showframe="true" data-padding="4" data-profileid="94dc5dca-2f81-11ea-866a-0bef29f386d0"><div class="rs-ltkwidget-container"><div ui-view=""></div></div></div><noscript>This content requires JavaScript to be enabled, and the site or browser may be disabling it. Try reactivating it to view this content.</noscript></div>

# Site Footer
copyright: "Twinkle Katoch"
footer:
  insta_at: 1246379710.bfe80e8.4e67c16985a24072a235c08fc5850f17
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      # url:
    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/twinklekatoch"

# Reading Files
include:
  - _pages
