remote_theme: hardpool/hardpool-flat

# Build settings
markdown: kramdown
encoding: utf-8

# Site Settings
title                     : "Twinkle's portfolio"
title_separator           : "|"
favicon                   : /assets/fav.ico
similar_posts:
  tags_to_match: 2

# Site SEO
seo:
  gtmid: GTM-M3MXT24

# Site Header
main_logo                 : ""
name                      : "Twinkle Katoch"
description               : ""
header:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/twinklekatoch"

# Site Footer
copyright: "Twinkle Katoch"
footer:
  insta_at: 1246379710.bfe80e8.4e67c16985a24072a235c08fc5850f17
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      # url:
    
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/twinklekatoch"

# Reading Files
include:
  - _pages
