remote_theme: hardpool/hardpool-flat

# Build settings
markdown: kramdown

# Site Settings
title                     : "Twinkle's portfolio"
title_separator           : "|"
favicon                   : /assets/fav.ico
similar_posts:
  tags_to_match: 2

# Site SEO
seo:
  gtmid: GTM-M3MXT24

# Site Header
main_logo                 : ""
name                      : "Twinkle Katoch"
description               : ""

# Site Footer
copyright: "Twinkle Katoch"
footer:
  insta_at: 1246379710.bfe80e8.4e67c16985a24072a235c08fc5850f17
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Reading Files
include:
  - _pages
